config/routes.rb
Myflix::Application.routes.draw do
  get 'ui(/:action)', controller: 'ui'

  root 'pages#front'
  get 'register', to: 'users#new'
  get 'home', to: 'videos#index'
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'
  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  get 'my_queue', to: 'queue_items#index'
  post 'my_queue', to: 'queue_items#destroy'
  post 'update_queue', to: 'queue_items#update_queue'
  get 'expired_token', to: 'pages#expired_token'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'

  resources :videos, only: :show do
    collection do
      get '/search', to: 'videos#search'
      get '/advanced_search', to: 'videos#advanced_search', as: :advanced_search
    end

    resources :reviews, only: :create
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: :index
  end

  resources :invitations, only: [:new, :create]
  resources :password_resets, only: [:show, :create]
  resources :forgot_passwords, only: :create
  resources :queue_items, only: [:create, :destroy]
  resources :categories, only: :show
  resources :sessions, only: :create
  resources :users, only: [:create, :show]

  get '/people', to: 'relationships#index'

  resources :relationships, only: [:create, :destroy]

  mount StripeEvent::Engine, at: '/stripe_events'
end

app/models/video.rb
class Video < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name ['myflix', Rails.env].join('_')
  document_type 'video'

  belongs_to :category
  has_many :reviews

  mount_uploader :large_cover, LargeCoverUploader
  mount_uploader :small_cover, SmallCoverUploader

  validates_presence_of :title, :description

  def self.search_by_title(title)
    return [] if title.blank?

    where('title ~* ?', title).order(created_at: :desc)
  end

  def rating
    return nil if reviews.size == 0
    average = reviews.map{ |review| review.rating }.reduce(&:+) / (reviews.size.to_f)
  end

  def total_reviews
    self.reviews.count
  end

  def self.search(query, options={})
    search_definition = {
      query: {
        bool: {
          must: {
            multi_match: {
              query: query,
              fields: ['title^100', 'description^50'],
              operator: 'and'
            }
          }
        }
      }
    }

    if query.present? && options[:reviews].present?
      search_definition[:query][:bool][:must][:multi_match][:fields] << 'reviews.body'
    end

    if options[:rating_from].present? || options[:rating_to].present?
      search_definition[:query][:bool][:filter] = {
        range: {
          rating: {
            gte: (options[:rating_from] if options[:rating_from].present?),
            lte: (options[:rating_to] if options[:rating_to].present?)
          }
        }
      }
    end

    __elasticsearch__.search(search_definition)
  end

  def as_indexed_json(options={})
    as_json(
      methods: [:rating],
      only: [:title, :description],
      include: {
        reviews: { only: [:body] }
      }
    )
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminsController
  def new
    @video = Video.new
  end

  def create
    @video = Video.create(video_params)
    if @video.save
      flash[:success] = "You have sucessfully added #{@video.title}"
      redirect_to new_admin_video_path
    else
      flash.now[:error] = "You can't add this video, please check the errors"
      render :new
    end
  end

  private

  def video_params
    params.require(:video).permit!
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :require_user

  def index
    @categories = Category.all
  end

  def show
    @video = VideoDecorator.decorate(Video.find(params[:id]))
    @reviews = @video.reviews.limit(10)
  end

  def search
    @videos = Video.search_by_title(params[:query])
  end

  def advanced_search
    options = {
      reviews: params[:reviews],
      rating_from: params[:rating_from],
      rating_to: params[:rating_to]
    }

    if params[:query]
      @videos =  Video.search(params[:query], options).records.to_a
    else
      @videos = []
    end
  end
end

app/views/videos/advanced_search.html.haml
%section.advanced_search.container
  %form.form-horizontal
    %header
      %h1 Advanced Search
    =form_tag advanced_search_videos_path, method: :get, class: 'form-horizontal' do
      .form-group
        .col-sm-6
          =search_field_tag :query, params[:query], class: 'form-control', placeholder: "Search videos by title, description"
      .form-group
        .col-sm-6
          .checkbox
            =label_tag do
              =check_box_tag 'reviews', 'y', params[:reviews] == 'y'
              Include Reviews
      .form-group
        .row.average_rating_label Average Rating
        =label_tag 'rating_from', 'From:', class: 'col-sm-1 control-label'
        .col-sm-2
          =select_tag 'rating_from', options_for_select((10..50).map { |num| num / 10.0 }, params[:rating_from]), { prompt: '-', class: 'form-control' }
        =label_tag 'rating_to', 'To:', class: 'col-sm-1 control contorl-label'
        .col-sm-2
          =select_tag 'rating_to', options_for_select((10..50).map { |num| num / 10.0 }, params[:rating_to]), { prompt: '-', class: 'form-control' }
      .form-group
        .col-sm-6
          = button_tag(type: "submit", class: "btn btn-primary") do
            %span.glyphicon.glyphicon-search
            Search
  %hr
  - if params[:query].present?
    %h2.results_count Results: #{@videos.size} videos found
    -@videos.each do |video|
      %article.video.row
        .video_data
          %figure.col-sm-2
            %img(src="#{video.small_cover_url}" alt="video cover")
          .video_body.col-sm-10
            %header
              %h3
                =video.title
            %p.video_description
              =video.description
            %hr
            .details
              %span.average_rating Average rating: #{video.rating}
              %span.reviews_count #{video.reviews.count} reviews
            -if video.reviews.count > 0
              %footer.video_review
                #{video.reviews.first.body}

app/views/videos/index.html.haml
- @categories.each do |cat, videos|
  - if cat.videos.length > 0
    %article.video_category
      %header
        %h3= link_to "#{cat.name.capitalize}", category_path(cat)
      .videos.row
        - cat.recent_videos.each do |video|
          .video.col-sm-2
            = link_to video_path(video), nil do
              %img(src="#{video.small_cover_url}")

app/views/videos/search.html.haml
.videos.row
  - @videos.each do |video|
    .video.col-sm-2
      = link_to video_path(video), nil do
        %img(src="#{video.small_cover_url}")

app/views/videos/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@video.large_cover_url}")
      .video_info.col-sm-3
        %header
          %h3 "#{@video.title}"
          %span Rating: #{@video.rating}
        %p "#{@video.description}"
        .actions
          %a.btn.btn-primary(href="#{@video.video_url}") Watch Now
          = link_to '+ My Queue', queue_items_path(video_id: @video.id), method: :post, class: 'btn btn-default' unless current_user.queued_video?(@video)

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      = form_for [@video, Review.new] do |f|
        %fieldset
          .form-group
            = f.label 'Rate this video'
            .row
              .col-sm-3
                = f.select(:rating, options_for_select([5, 4, 3, 2, 1].map { |num| [pluralize(num, 'Star')] }), {}, class: 'form-control')
          .form-group
            = f.label 'Write Review'
            .row
              .col-sm-8
                = f.text_area(:body, rows: 6, class: 'form-control')
        %fieldset.form-group.actions.clearfix
          = f.submit 'Submit', class: 'btn'
          = link_to 'Cancel', video_path(@video)
      %header
        %h3 User Reviews (#{@video.total_reviews})
      %ul
        - @reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %span Rating: #{review.rating} / 5
                %p
                  by
                  =link_to review.user.full_name, user_path(review.user)
              .col-sm-8
                %p #{review.body}