config/routes.rb
Myflix::Application.routes.draw do
  get 'ui(/:action)', controller: 'ui'

  root 'pages#front'
  get 'register', to: 'users#new'
  get 'home', to: 'videos#index'
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'
  get 'forgot_password', to: 'forgot_passwords#new'
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  get 'my_queue', to: 'queue_items#index'
  post 'my_queue', to: 'queue_items#destroy'
  post 'update_queue', to: 'queue_items#update_queue'
  get 'expired_token', to: 'pages#expired_token'
  get 'register/:token', to: 'users#new_with_invitation_token', as: 'register_with_token'

  resources :videos, only: :show do
    collection do
      get '/search', to: 'videos#search'
      get '/advanced_search', to: 'videos#advanced_search', as: :advanced_search
    end

    resources :reviews, only: :create
  end

  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: :index
  end

  resources :invitations, only: [:new, :create]
  resources :password_resets, only: [:show, :create]
  resources :forgot_passwords, only: :create
  resources :queue_items, only: [:create, :destroy]
  resources :categories, only: :show
  resources :sessions, only: :create
  resources :users, only: [:create, :show]

  get '/people', to: 'relationships#index'

  resources :relationships, only: [:create, :destroy]

  mount StripeEvent::Engine, at: '/stripe_events'
end

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "MyFLiX", root_path
  - if current_user
    %ul.col-md-3.clearfix
      %li= link_to "Videos", home_path
      %li= link_to "My Queue", my_queue_path
      %li= link_to "People", people_path
    %form.col-md-4.navbar-form(action="#{search_videos_path}")
      .form-group
        %input.form-control(type="text" name="query" placeholder="Search for videos here")
      %button.btn.btn-default(type="submit") Search
    =link_to 'Advanced Search', advanced_search_videos_path, html_options = { class: 'col-md-1 text-center'}
    #user_links.pull-right
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            Welcome, #{current_user.full_name}
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li
              = link_to 'Invite a friend', new_invitation_path
              %a(href="#") Account
              %a(href="#") Plan and Billing
              = link_to "Sign Out", sign_out_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    =content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)